services:
  api-prod:
    container_name: backend_container_prod
    env_file:
      - .env
    ports:
      - "8001:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend.pro
    restart: unless-stopped

  celery_worker_prod:
    container_name: celery_worker_container_prod
    env_file:
      - .env
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend.pro
    command: celery -A current worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - api-prod

  celery_beat_prod:
    container_name: celery_beat_container_prod
    env_file:
      - .env
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend.pro
    command: celery -A current beat --loglevel=info
    restart: unless-stopped
    depends_on:
      - api-prod
