sonar.projectKey=Current-Calendar_app
sonar.organization=current-calendar


sonar.sources=backend, frontend

sonar.exclusions=**/node_modules/**, **/.expo/**, **/migrations/**, **/venv/**, **/htmlcov/**, backend/manage.py

sonar.test.inclusions=backend/**/tests/**, backend/**/tests.py, backend/**/test_*.py


sonar.python.coverage.reportPaths=backend/coverage.xml

# sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info