import { StyleSheet } from 'react-native';

const profileStyles = StyleSheet.create({
    container: { flex: 1 },
    centerContent: { justifyContent: 'center', alignItems: 'center' },
    scrollView: { flex: 1 },
  profileSection: {
    width: '100%',
    maxWidth: 920,
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    maxWidth: 520,
    minHeight: 120,
    alignSelf: 'center',
    marginBottom: 4,
  },
    profilePictureContainer: {
      position: 'absolute',
      left: 0,
      top: 0,
      marginBottom: 0,
    },
    profilePicture: { width: 120, height: 120, borderRadius: 200, borderWidth: 2, borderColor: '#dbdbdb' },
    photoOverlay: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(0,0,0,0.55)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    photoOverlayText: { color: '#ffffff', fontSize: 16 },
    statsContainer: { width: '100%', flexDirection: 'column', alignItems: 'center' },
    statsRow: { flexDirection: 'row', gap: 26, marginTop: 14, justifyContent: 'center', alignSelf: 'center' },
    statItem: { alignItems: 'center' },
    statNumber: { fontSize: 18, fontWeight: '600', color: '#262626' },
    statLabel: { fontSize: 13, color: '#737373', marginTop: 2 },
    name: { fontSize: 18, fontWeight: '700', color: '#262626', textAlign: 'center' },
    fullname: { marginTop: 12, fontSize: 12, fontWeight: '600', color: '#262626' },
    pronouns: { fontSize: 12, fontWeight: '500', color: '#6868689a', marginBottom: 14, marginTop: 2, textAlign: 'center' },
    bioSection: { marginTop: 16, marginBottom: 22, alignItems: 'center' },
    bio: { fontSize: 14, color: '#262626', lineHeight: 20, textAlign: 'center', maxWidth: 560 },
    actionButton: {
      backgroundColor: '#eb8c85',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: 'center',
      marginBottom: 18,
      maxWidth: 500,
      minWidth: 220,
      alignSelf: 'center',
    },
    actionButtonAlt: { backgroundColor: '#e0e0e0' },
    actionButtonText: { fontSize: 14, fontWeight: '600', color: '#ffffff' },
    actionButtonTextAlt: { color: '#262626' },
    logoutButton: { 
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#10464D', 
    marginTop: 14,
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  logoutButtonText: { 
    color: '#10464D', 
    fontWeight: '600',
    fontSize: 16,
  },
    postsGrid: {
      width: '100%',
      maxWidth: 920,
      alignSelf: 'center',
      marginTop: 8,
      borderTopWidth: 1,
      borderTopColor: '#e0e0e0',
      alignItems: 'center',
    },
    gridHeaderText: {
      paddingVertical: 16,
      paddingHorizontal: 8,
      fontSize: 16,
      fontWeight: '600',
      color: '#262626',
      textAlign: 'center',
    },
    emptyText: { marginTop: 20, color: '#737373', fontStyle: 'italic', textAlign: 'center' },
    errorText: { marginTop: 10, color: '#737373', fontSize: 16 }
});

export default profileStyles;
