# Generated by Django 5.2.11 on 2026-03-17 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE main_calendar "
                        "ADD COLUMN IF NOT EXISTS likes_count integer NOT NULL DEFAULT 0;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE main_calendar "
                        "DROP COLUMN IF EXISTS likes_count;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="calendar",
                    name="likes_count",
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE TABLE IF NOT EXISTS main_calendarlike ("
                        "id bigserial PRIMARY KEY, "
                        "created_at timestamp with time zone NOT NULL DEFAULT now(), "
                        "calendar_id bigint NOT NULL REFERENCES main_calendar(id) DEFERRABLE INITIALLY DEFERRED, "
                        "user_id bigint NOT NULL REFERENCES main_user(id) DEFERRABLE INITIALLY DEFERRED"
                        ");"
                    ),
                    reverse_sql="DROP TABLE IF EXISTS main_calendarlike;",
                ),
                migrations.RunSQL(
                    sql=(
                        "CREATE INDEX IF NOT EXISTS main_calendarlike_calendar_id_"
                        "idx ON main_calendarlike (calendar_id);"
                    ),
                    reverse_sql="DROP INDEX IF EXISTS main_calendarlike_calendar_id_idx;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="CalendarLike",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                        (
                            "calendar",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="main.calendar"),
                        ),
                        (
                            "user",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_likes", to=settings.AUTH_USER_MODEL),
                        ),
                    ],
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "DO $$ "
                        "BEGIN "
                        "IF NOT EXISTS ("
                        "SELECT 1 FROM pg_constraint WHERE conname = 'unique_calendar_like_per_user'"
                        ") THEN "
                        "ALTER TABLE main_calendarlike "
                        "ADD CONSTRAINT unique_calendar_like_per_user UNIQUE (user_id, calendar_id); "
                        "END IF; "
                        "END $$;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE main_calendarlike "
                        "DROP CONSTRAINT IF EXISTS unique_calendar_like_per_user;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="calendarlike",
                    constraint=models.UniqueConstraint(fields=("user", "calendar"), name="unique_calendar_like_per_user"),
                ),
            ],
        ),
    ]
