# Generated by Django 5.2.11 on 2026-03-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('INAPPROPRIATE_CONTENT', 'Inappropriate Content'), ('SPAM', 'Spam'), ('HARASSMENT', 'Harassment'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
