# Generated by Django 5.2.11 on 2026-02-24 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pronombres',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='recurrencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
