# Generated by Django 5.2.11 on 2026-03-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calendar_likes'),
        ('main', '0002_report'),
    ]

    operations = [
    ]
