# Generated by Django 5.2.11 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calendario_fecha_creacion_evento_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
