# Generated by Django 5.2.11 on 2026-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calendario_fecha_creacion_evento_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='calendario',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='calendarios', to='main.etiquetacalendario'),
        ),
    ]
