# Generated by Django 5.2.11 on 2026-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='calendars', to='main.calendarlabel'),
        ),
    ]
