# Generated by Django 5.2.11 on 2026-03-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_calendar_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='calendars', to='main.label'),
        ),
        migrations.AddField(
            model_name='event',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.label'),
        ),
    ]
